kind: Service
apiVersion: v1
metadata:
  name: eia
  labels:
    app: eia
spec:
  type: ClusterIP
  selector:
    app: eia
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: eia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eia
  template:
    metadata:
      labels:
        app: eia
        version: v1
    spec:
      containers:
      - name: eia
        image: eia
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
